name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'

      - name: Build
        run: dotnet build JpkEdytor.sln -c 'Release' -v 'normal' -p:Version=1.0.0.0

      - name: Run unit tests
        run: dotnet test JpkEdytor.sln -c 'Release' -v 'normal' --no-build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: JpkEdytor
          path: JpkEdytor/bin/Release/net45/JpkEdytor.exe
