name: CI

on: push

jobs:

  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '6.0.x'

      - name: Build
        run: dotnet build JpkEdytor.sln -c 'Release' -v 'normal'

      - name: Run unit tests
        run: dotnet test JpkEdytor.sln -c 'Release' -v 'normal' -l "console;verbosity=normal" --no-build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          name: JpkEdytor
          path: JpkEdytor/bin/Release/net48/JpkEdytor.exe
